// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  bookSidebar: [
    {
      type: 'category',
      label: 'Front Matter',
      link: {
        type: 'generated-index',
        title: 'Front Matter',
        description: 'Important preliminary sections of the book.',
        slug: '/category/front-matter',
      },
      items: [
        'front-matter/intro',
        'front-matter/preface',
        'front-matter/how-to-use-this-ai-native-textbook',
        'front-matter/hardware-requirements',
        'front-matter/course-roadmap',
      ],
    },
    {
      type: 'category',
      label: 'PART I — Foundations of Physical AI',
      link: {
        type: 'generated-index',
        title: 'Foundations of Physical AI',
        description: 'Understand the core concepts of Physical AI.',
        slug: '/category/part-i-foundations',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'part1-foundations',
        },
      ],
    },
    {
      type: 'category',
      label: 'PART II — ROS 2: The Robotic Nervous System',
      link: {
        type: 'generated-index',
        title: 'ROS 2: The Robotic Nervous System',
        description: 'Dive deep into ROS 2 for robotics.',
        slug: '/category/part-ii-ros2',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'part2-ros2',
        },
      ],
    },
    {
      type: 'category',
      label: 'PART III — Simulation & Digital Twins (Gazebo + Unity)',
      link: {
        type: 'generated-index',
        title: 'Simulation & Digital Twins',
        description: 'Explore simulation environments for robotics.',
        slug: '/category/part-iii-simulation',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'part3-simulation',
        },
      ],
    },
    {
      type: 'category',
      label: 'PART IV — NVIDIA Isaac: The AI-Robot Brain',
      link: {
        type: 'generated-index',
        title: 'NVIDIA Isaac: The AI-Robot Brain',
        description: 'Learn about the NVIDIA Isaac platform.',
        slug: '/category/part-iv-isaac',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'part4-isaac',
        },
      ],
    },
    {
      type: 'category',
      label: 'PART V — Vision-Language-Action Systems',
      link: {
        type: 'generated-index',
        title: 'Vision-Language-Action Systems',
        description: 'Understand VLA systems in robotics.',
        slug: '/category/part-v-vla',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'part5-vla',
        },
      ],
    },
    {
      type: 'category',
      label: 'PART VI — Humanoid Robotics Engineering',
      link: {
        type: 'generated-index',
        title: 'Humanoid Robotics Engineering',
        description: 'Engineering aspects of humanoid robots.',
        slug: '/category/part-vi-engineering',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'part6-humanoid-engineering',
        },
      ],
    },
    {
      type: 'category',
      label: 'PART VII — Capstone Project',
      link: {
        type: 'generated-index',
        title: 'Capstone Project',
        description: 'Integrate knowledge in a capstone project.',
        slug: '/category/part-vii-capstone',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'part7-capstone-project',
        },
      ],
    },
    {
      type: 'category',
      label: 'Appendices',
      link: {
        type: 'generated-index',
        title: 'Appendices',
        description: 'Additional resources and installations.',
        slug: '/category/appendices',
      },
      items: [
        'appendices/ubuntu-installation',
        'appendices/ros2-setup',
        'appendices/jetson-orin-setup',
        'appendices/realsense-camera-setup',
        'appendices/hardware-buying-guide',
      ],
    },
  ],
};

export default sidebars;
